-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 01:29:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workers` (
  `id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `experience` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Workers_Users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workers_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `cars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clients_Users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_Clients_Cars1_idx` (`cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clients_Cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  `workers_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  `cars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Workers1_idx` (`workers_id` ASC) VISIBLE,
  INDEX `fk_Orders_Clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_Orders_Cars1_idx` (`cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `mydb`.`Workers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orders_Clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`Clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orders_Cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_Stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders_has_Service_Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders_has_Service_Stations` (
  `orders_id` INT NOT NULL,
  `service_Stations_id` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `service_Stations_id`),
  INDEX `fk_Orders_has_Service_Stations_Service_Stations1_idx` (`service_Stations_id` ASC) VISIBLE,
  INDEX `fk_Orders_has_Service_Stations_Orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Service_Stations_Orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orders_has_Service_Stations_Service_Stations1`
    FOREIGN KEY (`service_Stations_id`)
    REFERENCES `mydb`.`Service_Stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers_has_Service_Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workers_has_Service_Stations` (
  `workers_id` INT NOT NULL,
  `service_Stations_id` INT NOT NULL,
  PRIMARY KEY (`workers_id`, `service_Stations_id`),
  INDEX `fk_Workers_has_Service_Stations_Service_Stations1_idx` (`service_Stations_id` ASC) VISIBLE,
  INDEX `fk_Workers_has_Service_Stations_Workers1_idx` (`workers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workers_has_Service_Stations_Workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `mydb`.`Workers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Workers_has_Service_Stations_Service_Stations1`
    FOREIGN KEY (`service_Stations_id`)
    REFERENCES `mydb`.`Service_Stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lifts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cutters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cutters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hydraulic_Presses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hydraulic_Presses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tire_Changers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tire_Changers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compressors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compressors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture` VARCHAR(45) NULL,
  `perfomance` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equpments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equpments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lifts_id` INT NOT NULL,
  `cutters_id` INT NOT NULL,
  `hydraulic_Presses_id` INT NOT NULL,
  `tire_changers_id` INT NOT NULL,
  `Compressors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Equpmints_Lifts1_idx` (`lifts_id` ASC) VISIBLE,
  INDEX `fk_Equpmints_Cutters1_idx` (`cutters_id` ASC) VISIBLE,
  INDEX `fk_Equpments_Hydraulic_Presses1_idx` (`hydraulic_Presses_id` ASC) VISIBLE,
  INDEX `fk_Equpments_Tire_Changers1_idx` (`tire_changers_id` ASC) VISIBLE,
  INDEX `fk_Equpments_Compressors1_idx` (`Compressors_id` ASC) VISIBLE,
  CONSTRAINT `fk_Equpmints_Lifts1`
    FOREIGN KEY (`lifts_id`)
    REFERENCES `mydb`.`Lifts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equpmints_Cutters1`
    FOREIGN KEY (`cutters_id`)
    REFERENCES `mydb`.`Cutters` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equpments_Hydraulic_Presses1`
    FOREIGN KEY (`hydraulic_Presses_id`)
    REFERENCES `mydb`.`Hydraulic_Presses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equpments_Tire_Changers1`
    FOREIGN KEY (`tire_changers_id`)
    REFERENCES `mydb`.`Tire_Changers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equpments_Compressors1`
    FOREIGN KEY (`Compressors_id`)
    REFERENCES `mydb`.`Compressors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_Stations_has_Equpments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_Stations_has_Equpments` (
  `service_Stations_id` INT NOT NULL,
  `equpments_id` INT NOT NULL,
  PRIMARY KEY (`service_Stations_id`, `equpments_id`),
  INDEX `fk_Service_Stations_has_Equpments_Equpments1_idx` (`equpments_id` ASC) VISIBLE,
  INDEX `fk_Service_Stations_has_Equpments_Service_Stations1_idx` (`service_Stations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Service_Stations_has_Equpments_Service_Stations1`
    FOREIGN KEY (`service_Stations_id`)
    REFERENCES `mydb`.`Service_Stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Service_Stations_has_Equpments_Equpments1`
    FOREIGN KEY (`equpments_id`)
    REFERENCES `mydb`.`Equpments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
